In [1]:
import os
import csv
import numpy as np
import pandas as pd
import math
import pickle

import torch
from torch.utils.data import Dataset
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import vocab, build_vocab_from_iterator
from collections import OrderedDict, Counter

from tqdm import tqdm

In [6]:
class IIIT5KDataset(Dataset):
    def __init__(self, split=None, directory='dataset/'):
        super(IIIT5KDataset).__init__()
        imgs = list()
        lbls = list()
        bboxes = list()
        
        for i in range(10):
            file_name = directory + f'shard_{i}.pkl'
            temp_pickle = pd.read_pickle(file_name)
            imgs = imgs + temp_pickle[0]
            lbls = lbls + temp_pickle[1]
            bboxes = bboxes + temp_pickle[2]
            
        self.images = imgs
        self.labels = lbls
        self.bbox = bboxes
        
    def __getitem__(self, index):
        img = self.images[index]
        lbl = self.labels[index]
        bbox = self.bbox[index]
        
        return (img, lbl, bbox)

In [8]:
if 'temp' in locals():
    del temp

temp = IIIT5KDataset(directory='dataset/')
temp.__getitem__(0)

(array([[0.9844, 0.9805, 0.9844, ..., 0.4746, 0.4785, 0.4824],
        [0.7217, 0.7334, 0.741 , ..., 0.4785, 0.4824, 0.4902],
        [0.4587, 0.4824, 0.4785, ..., 0.4785, 0.4824, 0.4863],
        ...,
        [0.4746, 0.4785, 0.4863, ..., 0.4746, 0.4863, 0.4941],
        [0.4863, 0.4824, 0.4863, ..., 0.4785, 0.4785, 0.4824],
        [0.4863, 0.4824, 0.4824, ..., 0.4785, 0.4785, 0.4824]],
       dtype=float16),
 'You',
 [array([ 6.4102564,  3.7209303, 26.923077 , 26.790697 ], dtype=float32),
  array([32.05128 , 11.16279 , 30.76923 , 19.348837], dtype=float32),
  array([62.820515,  8.186047, 32.05128 , 20.83721 ], dtype=float32)])

In [11]:
image, label, bbox = temp[5]
label

'DODA'